import type { Treatment } from '../types';

/**
 * 香港市場常見儀器類療程（激光、射頻、超聲波等）。
 *
 * ⚠️ 高能量激光及彩光屬香港衞生署界定嘅高風險程序，須由註冊醫生施行。
 * 價格為 2025–2026 年市場參考區間。
 */

const DOCTOR_ONLY = '香港：高能量激光 / 彩光屬高風險程序，須由註冊醫生施行';
const THERAPIST_OK = '一般由受訓治療師施行，建議先經醫生評估';

export const DEVICES: Treatment[] = [
  // ────────────────────────── 聚焦超聲波（HIFU） ──────────────────────────
  {
    id: 'ultherapy',
    name: 'Ultherapy 超聲刀',
    brand: 'Ultherapy / Ulthera (Merz)',
    category: 'device',
    family: '微聚焦超聲波 + 實時超聲影像 (MFU-V)',
    mechanism: '將超聲波能量精準聚焦於 1.5 / 3.0 / 4.5mm 深度（含 SMAS 筋膜層），造成熱凝固點刺激膠原收縮同新生。',
    indications: [
      { key: 'skin_laxity', efficacy: 5 },
      { key: 'jowls', efficacy: 5 },
      { key: 'jawline_definition', efficacy: 4 },
      { key: 'brow_ptosis', efficacy: 4 },
      { key: 'neck_laxity', efficacy: 4 },
      { key: 'upper_eyelid_hooding', efficacy: 3 },
    ],
    sessions: '1 次',
    interval: '12–18 個月',
    onset: '2–3 個月漸進',
    duration: '12–18 個月',
    downtimeDays: [0, 2],
    priceHKD: { min: 15000, max: 30000, unit: '每次（600 lines 全面 + 頸）' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '治療區有金屬植入物 / 心臟起搏器', '嚴重活躍暗瘡', '面部填充劑未穩定（建議相隔 2 週）'],
    notes: '唯一有實時影像導航嘅 HIFU，可睇住層次打，安全度高但價錢貴。過瘦人士可能出現面部凹陷。',
  },
  {
    id: 'ultraformer',
    name: 'Ultraformer III / MPT',
    brand: 'Ultraformer (Classys)',
    category: 'device',
    family: '微聚焦超聲波 (HIFU)',
    mechanism: '多種深度探頭（1.5–13mm）作緊膚提升及局部溶脂，性價比高。',
    indications: [
      { key: 'skin_laxity', efficacy: 4 },
      { key: 'jowls', efficacy: 4 },
      { key: 'jawline_definition', efficacy: 4 },
      { key: 'submental_fat', efficacy: 3 },
      { key: 'neck_laxity', efficacy: 3 },
    ],
    sessions: '1 次；可 6–12 個月重覆',
    interval: '6–12 個月',
    onset: '1–3 個月',
    duration: '9–12 個月',
    downtimeDays: [0, 2],
    priceHKD: { min: 3000, max: 12000, unit: '每次（視乎發數）' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '治療區金屬植入物', '活躍皮膚感染'],
    notes: '香港最普及嘅 HIFU，價錢按「發數」計，比較發數要留意探頭深度而唔淨係睇總數。',
  },
  {
    id: 'sofwave',
    name: 'Sofwave 音波拉皮',
    brand: 'Sofwave',
    category: 'device',
    family: '同步平行超聲波 (SUPERB)',
    mechanism: '於中真皮層（約 1.5mm）產生均勻熱能，痛感較低，安全性高。',
    indications: [
      { key: 'skin_laxity', efficacy: 4 },
      { key: 'texture', efficacy: 3 },
      { key: 'jowls', efficacy: 3 },
      { key: 'brow_ptosis', efficacy: 3 },
    ],
    sessions: '1–2 次',
    interval: '12 個月',
    onset: '6–12 星期',
    duration: '約 12 個月',
    downtimeDays: [0, 1],
    priceHKD: { min: 15000, max: 28000, unit: '每次' },
    risk: 'low',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '治療區金屬植入物'],
    notes: '深度較淺，唔會做到 SMAS 層，適合輕度鬆弛或怕痛人士。',
  },

  // ────────────────────────── 射頻 ──────────────────────────
  {
    id: 'thermage',
    name: 'Thermage FLX 電波拉皮',
    brand: 'Thermage FLX (Solta)',
    category: 'device',
    family: '單極射頻 (Monopolar RF)',
    mechanism: '體積式加熱真皮至 65–75°C，令膠原即時收縮並啟動長達 6 個月嘅新生。',
    indications: [
      { key: 'skin_laxity', efficacy: 5 },
      { key: 'texture', efficacy: 4 },
      { key: 'jowls', efficacy: 4 },
      { key: 'pores', efficacy: 3 },
      { key: 'neck_laxity', efficacy: 3 },
    ],
    sessions: '1 次',
    interval: '12–18 個月',
    onset: '即時緊緻 + 3–6 個月漸進',
    duration: '12–24 個月',
    downtimeDays: [0, 1],
    priceHKD: { min: 12000, max: 26000, unit: '每次（900 發全面）' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '心臟起搏器 / 植入式除顫器', '治療區金屬植入物'],
    notes: '偏向「緊緻 + 收細毛孔」，提升力度不及 HIFU；常同 HIFU 一齊做（一緊一提）。',
  },
  {
    id: 'morpheus8',
    name: 'Morpheus8 微針射頻',
    brand: 'Morpheus8 (InMode)',
    category: 'device',
    family: '射頻微針 (RF Microneedling)',
    mechanism: '絕緣微針刺入真皮（可達 8mm）釋放射頻，同時重塑膠原及溶解淺層脂肪。',
    indications: [
      { key: 'acne_scar', efficacy: 5 },
      { key: 'pores', efficacy: 5 },
      { key: 'texture', efficacy: 4 },
      { key: 'skin_laxity', efficacy: 4 },
      { key: 'jowls', efficacy: 4 },
      { key: 'submental_fat', efficacy: 3 },
    ],
    sessions: '3 次為一個療程',
    interval: '每次相隔 4–6 星期',
    onset: '3–6 星期',
    duration: '12–18 個月',
    downtimeDays: [2, 5],
    priceHKD: { min: 6000, max: 15000, unit: '每次' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '活躍皮膚感染', '正服食異維 A 酸（建議停藥 6 個月）', '疤痕增生體質'],
    notes: '深膚色相對安全（能量繞過表皮黑色素），係凹凸洞嘅主力療程之一。',
  },
  {
    id: 'sylfirm',
    name: 'Sylfirm X',
    brand: 'Sylfirm X (Viol)',
    category: 'device',
    family: '雙極脈衝射頻微針 (RP Microneedling)',
    mechanism: '獨有脈衝波模式可選擇性作用於異常血管同色素，係少數可安全處理黃褐斑嘅儀器。',
    indications: [
      { key: 'melasma', efficacy: 5 },
      { key: 'redness', efficacy: 5 },
      { key: 'pih', efficacy: 4 },
      { key: 'pores', efficacy: 4 },
      { key: 'acne_scar', efficacy: 4 },
      { key: 'skin_laxity', efficacy: 3 },
    ],
    sessions: '3–5 次',
    interval: '每次相隔 2–4 星期',
    onset: '2–4 星期',
    duration: '需持續維持',
    downtimeDays: [1, 3],
    priceHKD: { min: 4000, max: 10000, unit: '每次' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '活躍感染', '心臟起搏器'],
    notes: '黃褐斑病人首選之一，因為傳統激光容易令黃褐斑反黑。',
  },
  {
    id: 'oligio',
    name: 'Oligio 黑鑽電波',
    brand: 'Oligio (Jeisys)',
    category: 'device',
    family: '單極射頻 (Monopolar RF)',
    mechanism: '與 Thermage 同類原理，配備自動化溫控，價格較親民。',
    indications: [
      { key: 'skin_laxity', efficacy: 4 },
      { key: 'texture', efficacy: 3 },
      { key: 'pores', efficacy: 3 },
      { key: 'jowls', efficacy: 3 },
    ],
    sessions: '1 次',
    interval: '9–12 個月',
    onset: '即時 + 3 個月',
    duration: '9–15 個月',
    downtimeDays: [0, 1],
    priceHKD: { min: 6000, max: 15000, unit: '每次' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '心臟起搏器', '治療區金屬植入物'],
  },

  // ────────────────────────── 激光：色素 ──────────────────────────
  {
    id: 'picolaser',
    name: '皮秒激光',
    brand: 'PicoSure / PicoWay / Discovery Pico / PicoCare',
    category: 'device',
    family: '皮秒激光 (Picosecond Laser)',
    mechanism: '兆分之一秒脈衝以光機械效應震碎色素粒子，熱損傷極低；蜂巢透鏡模式可刺激膠原。',
    indications: [
      { key: 'pigmentation', efficacy: 5 },
      { key: 'pih', efficacy: 5 },
      { key: 'texture', efficacy: 4 },
      { key: 'acne_scar', efficacy: 4 },
      { key: 'pores', efficacy: 3 },
      { key: 'melasma', efficacy: 3 },
    ],
    sessions: '4–6 次',
    interval: '每次相隔 3–4 星期',
    onset: '1–2 次後可見',
    duration: '需防曬維持，否則復發',
    downtimeDays: [0, 3],
    priceHKD: { min: 1500, max: 5000, unit: '每次（全面）' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '近期曬傷', '正服食光敏感藥物', '活躍疱疹'],
    notes: '黃褐斑要用低能量、多次數，能量過高會反黑（PIH），亞洲膚色尤其要小心。',
  },
  {
    id: 'laser-toning',
    name: '激光去斑 / Laser Toning',
    brand: 'Q-switched Nd:YAG (Spectra / Revlite)',
    category: 'device',
    family: '調Q開關激光 (Q-switched Laser)',
    mechanism: '低能量高頻次擊碎表淺色素，適合大範圍膚色不均。',
    indications: [
      { key: 'melasma', efficacy: 4 },
      { key: 'pigmentation', efficacy: 4 },
      { key: 'pih', efficacy: 3 },
      { key: 'texture', efficacy: 3 },
    ],
    sessions: '6–10 次',
    interval: '每次相隔 1–2 星期',
    onset: '3–4 次後',
    duration: '需維持',
    downtimeDays: [0, 1],
    priceHKD: { min: 800, max: 2500, unit: '每次' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '近期曬傷', '光敏感藥物'],
    notes: '過度密集治療可致「白斑」（色素脫失），需嚴格控制次數。',
  },

  // ────────────────────────── 激光：血管 ──────────────────────────
  {
    id: 'vbeam',
    name: 'Vbeam 血管激光',
    brand: 'Vbeam Perfecta / Prima (Candela)',
    category: 'device',
    family: '脈衝染料激光 (PDL, 595nm)',
    mechanism: '被血紅素選擇性吸收，封閉異常擴張嘅微絲血管。',
    indications: [
      { key: 'redness', efficacy: 5 },
      { key: 'pih', efficacy: 4 },
      { key: 'acne_active', efficacy: 3 },
      { key: 'acne_scar', efficacy: 3 },
    ],
    sessions: '3–5 次',
    interval: '每次相隔 3–4 星期',
    onset: '1–2 次後',
    duration: '玫瑰痤瘡需長期維持',
    downtimeDays: [0, 5],
    priceHKD: { min: 2500, max: 6000, unit: '每次' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '光敏感藥物', '近期曬傷'],
    notes: '高能量設定會出現紫斑（purpura），約 5–7 日消退，做之前要問清楚。',
  },
  {
    id: 'ipl-m22',
    name: 'M22 彩光 / BBL',
    brand: 'Lumenis M22 / Sciton BBL Hero',
    category: 'device',
    family: '強脈衝光 (IPL / BBL)',
    mechanism: '寬光譜配濾片同時處理色素同血管，適合整體膚色改善。',
    indications: [
      { key: 'pigmentation', efficacy: 4 },
      { key: 'redness', efficacy: 4 },
      { key: 'texture', efficacy: 3 },
      { key: 'pores', efficacy: 3 },
      { key: 'acne_active', efficacy: 3 },
    ],
    sessions: '4–6 次',
    interval: '每次相隔 3–4 星期',
    onset: '2–3 次後',
    duration: '需維持',
    downtimeDays: [0, 3],
    priceHKD: { min: 1200, max: 4000, unit: '每次' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '近期曬黑 / 曬傷', '光敏感藥物', '黃褐斑（可能加重）'],
  },

  // ────────────────────────── 激光：換膚 / 疤痕 ──────────────────────────
  {
    id: 'fotona-4d',
    name: 'Fotona 4D 熱拉提',
    brand: 'Fotona SP Dynamis',
    category: 'device',
    family: 'Er:YAG + Nd:YAG 雙波長激光',
    mechanism: '由口腔內部及外部四個階段加熱，緊緻兼改善法令紋、膚質。',
    indications: [
      { key: 'skin_laxity', efficacy: 4 },
      { key: 'nasolabial_fold', efficacy: 3 },
      { key: 'texture', efficacy: 4 },
      { key: 'pores', efficacy: 3 },
      { key: 'perioral_lines', efficacy: 3 },
    ],
    sessions: '3–4 次',
    interval: '每次相隔 3–4 星期',
    onset: '2–4 星期',
    duration: '6–12 個月',
    downtimeDays: [0, 2],
    priceHKD: { min: 4000, max: 9000, unit: '每次' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '口腔潰瘍或感染', '光敏感藥物'],
  },
  {
    id: 'co2-fractional',
    name: '二氧化碳點陣激光',
    brand: 'Fractional CO2 (10600nm)',
    category: 'device',
    family: '汽化式點陣激光 (Ablative Fractional)',
    mechanism: '氣化微小柱狀組織，觸發深層重建，係凹凸洞同深紋最強嘅非手術方案。',
    indications: [
      { key: 'acne_scar', efficacy: 5 },
      { key: 'texture', efficacy: 5 },
      { key: 'pores', efficacy: 4 },
      { key: 'perioral_lines', efficacy: 4 },
      { key: 'skin_laxity', efficacy: 3 },
    ],
    sessions: '2–4 次',
    interval: '每次相隔 6–8 星期',
    onset: '1–3 個月',
    duration: '長效（結構性改善）',
    downtimeDays: [5, 10],
    priceHKD: { min: 3000, max: 9000, unit: '每次' },
    risk: 'high',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '正服食異維 A 酸（停藥 6–12 個月）', '疤痕增生體質', '活躍感染', '深膚色需謹慎'],
    notes: '亞洲人反黑（PIH）風險高，術前術後必須嚴格防曬 + 美白藥膏。停工期最長。',
  },
  {
    id: 'clear-brilliant',
    name: 'Clear + Brilliant 嫩膚激光',
    brand: 'Clear + Brilliant (Solta)',
    category: 'device',
    family: '非汽化式點陣激光 (Non-ablative)',
    mechanism: '溫和點陣加熱改善膚質、細紋同色調，俗稱「午餐激光」。',
    indications: [
      { key: 'texture', efficacy: 4 },
      { key: 'pores', efficacy: 4 },
      { key: 'pigmentation', efficacy: 3 },
      { key: 'dehydration', efficacy: 3 },
    ],
    sessions: '4–6 次',
    interval: '每次相隔 2–4 星期',
    onset: '2–3 次後',
    duration: '需維持',
    downtimeDays: [0, 2],
    priceHKD: { min: 2500, max: 5500, unit: '每次' },
    risk: 'low',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕', '活躍感染', '近期曬傷'],
  },

  // ────────────────────────── 身體 / 局部脂肪 ──────────────────────────
  {
    id: 'coolsculpting',
    name: 'CoolSculpting 冷凍溶脂',
    brand: 'CoolSculpting Elite (Allergan)',
    category: 'device',
    family: '冷凍脂肪分解 (Cryolipolysis)',
    mechanism: '控溫冷凍令脂肪細胞凋亡，經淋巴代謝排出；有頜下專用探頭。',
    indications: [{ key: 'submental_fat', efficacy: 4 }],
    sessions: '1–2 次',
    interval: '每次相隔 8–12 星期',
    onset: '8–12 星期',
    duration: '長期（脂肪細胞數量減少）',
    downtimeDays: [0, 3],
    priceHKD: { min: 4000, max: 9000, unit: '每個探頭' },
    risk: 'low',
    regulation: THERAPIST_OK,
    contraindications: ['冷球蛋白血症 / 冷凝集素病', '陣發性冷性血紅蛋白尿', '懷孕', '治療區疝氣'],
    notes: '罕見但真實嘅副作用：反常性脂肪增生（PAH），發生率約 1/3000–1/5000。',
  },
  {
    id: 'emface',
    name: 'Emface',
    brand: 'Emface (BTL)',
    category: 'device',
    family: '同步射頻 + HIFES 肌肉刺激',
    mechanism: '同時加熱膠原及選擇性刺激額肌與顴大肌收縮，屬「非注射式」提升。',
    indications: [
      { key: 'skin_laxity', efficacy: 3 },
      { key: 'midface_volume_loss', efficacy: 3 },
      { key: 'brow_ptosis', efficacy: 3 },
      { key: 'forehead_lines', efficacy: 2 },
    ],
    sessions: '4 次為一個療程',
    interval: '每次相隔 1 星期',
    onset: '4–8 星期',
    duration: '約 12 個月（建議每年維持）',
    downtimeDays: [0, 0],
    priceHKD: { min: 8000, max: 15000, unit: '每次' },
    risk: 'low',
    regulation: THERAPIST_OK,
    contraindications: ['懷孕', '心臟起搏器', '治療區金屬植入物', '癲癇'],
    notes: '零停工期，但效果溫和，適合唔想打針嘅客人。',
  },

  // ────────────────────────── 護理級 ──────────────────────────
  {
    id: 'hydrafacial',
    name: 'HydraFacial 水磨嫩膚',
    brand: 'HydraFacial (BeautyHealth)',
    category: 'device',
    family: '真空渦流清潔 + 精華導入',
    mechanism: '同步去角質、吸走粉刺、導入精華，即時提亮零停工。',
    indications: [
      { key: 'pores', efficacy: 3 },
      { key: 'texture', efficacy: 3 },
      { key: 'oiliness', efficacy: 3 },
      { key: 'acne_active', efficacy: 3 },
      { key: 'dehydration', efficacy: 3 },
    ],
    sessions: '每月 1 次維持',
    interval: '每月',
    onset: '即時',
    duration: '2–4 星期',
    downtimeDays: [0, 0],
    priceHKD: { min: 1200, max: 2800, unit: '每次' },
    risk: 'low',
    regulation: THERAPIST_OK,
    contraindications: ['活躍嚴重暗瘡發炎期', '對水楊酸過敏'],
  },
  {
    id: 'chemical-peel',
    name: '化學換膚（果酸 / 水楊酸）',
    brand: 'AHA / BHA / TCA Peel',
    category: 'device',
    family: '化學換膚 (Chemical Peel)',
    mechanism: '控制性剝脫角質層，加快代謝、疏通毛孔、淡化表淺色素。',
    indications: [
      { key: 'acne_active', efficacy: 4 },
      { key: 'pih', efficacy: 4 },
      { key: 'texture', efficacy: 4 },
      { key: 'pores', efficacy: 3 },
      { key: 'oiliness', efficacy: 3 },
      { key: 'melasma', efficacy: 3 },
    ],
    sessions: '4–6 次',
    interval: '每次相隔 2–4 星期',
    onset: '2–3 次後',
    duration: '需維持',
    downtimeDays: [1, 5],
    priceHKD: { min: 800, max: 3000, unit: '每次' },
    risk: 'medium',
    regulation: '淺層換膚可由治療師施行；中深層換膚屬高風險程序，須註冊醫生',
    contraindications: ['懷孕（部分成分）', '活躍疱疹', '近期曬傷', '正服食異維 A 酸'],
  },
  {
    id: 'microneedling',
    name: '微針療程',
    brand: 'Dermapen / SkinPen',
    category: 'device',
    family: '機械式微針 (Microneedling)',
    mechanism: '微創穿刺誘發傷口癒合反應，重建膠原並提升活性成分吸收。',
    indications: [
      { key: 'acne_scar', efficacy: 4 },
      { key: 'pores', efficacy: 4 },
      { key: 'texture', efficacy: 4 },
      { key: 'dehydration', efficacy: 3 },
    ],
    sessions: '4–6 次',
    interval: '每次相隔 4 星期',
    onset: '3–6 星期',
    duration: '需維持',
    downtimeDays: [1, 4],
    priceHKD: { min: 1500, max: 3500, unit: '每次' },
    risk: 'low',
    regulation: THERAPIST_OK,
    contraindications: ['活躍暗瘡發炎期', '疤痕增生體質', '正服食異維 A 酸', '活躍感染'],
  },
];
