import type { Treatment } from '../types';

/**
 * 香港市場常見注射類療程。
 *
 * ⚠️ 香港衞生署將注射性醫學美容程序（肉毒桿菌素、皮膚填充劑等）列為
 * 須由註冊醫生施行嘅高風險程序。價格為 2025–2026 年市場參考區間，
 * 個別診所差異可以好大，只作預算估算用。
 */

const DOCTOR_ONLY = '香港：注射程序須由註冊醫生施行（衞生署高風險美容程序）';

export const INJECTABLES: Treatment[] = [
  // ────────────────────────── 肉毒桿菌素 ──────────────────────────
  {
    id: 'btx-masseter',
    name: '肉毒瘦面（咬肌）',
    brand: 'Botox / Dysport / Xeomin / Botulax / Nabota',
    category: 'injectable',
    family: '肉毒桿菌素 (Botulinum Toxin A)',
    mechanism: '阻斷神經肌肉訊號，令肥大嘅咬肌逐步萎縮，面部下半部收窄。',
    indications: [
      { key: 'masseter_hypertrophy', efficacy: 5 },
      { key: 'jawline_definition', efficacy: 3 },
    ],
    sessions: '1 次；首年建議 2–3 次鞏固',
    interval: '4–6 個月',
    onset: '2–4 星期開始，6–8 星期最明顯',
    duration: '4–6 個月',
    downtimeDays: [0, 1],
    priceHKD: { min: 2000, max: 6000, unit: '每次（雙側）' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕/哺乳', '神經肌肉疾病（如重症肌無力）', '注射部位感染', '對配方成分過敏'],
    notes: '過量或位置唔啱可致咀嚼無力、面頰凹陷、笑容不對稱。',
  },
  {
    id: 'btx-upper-face',
    name: '肉毒除皺（上面部）',
    brand: 'Botox / Dysport / Xeomin',
    category: 'injectable',
    family: '肉毒桿菌素 (Botulinum Toxin A)',
    mechanism: '放鬆額肌、皺眉肌、眼輪匝肌，撫平因表情產生嘅動態紋。',
    indications: [
      { key: 'forehead_lines', efficacy: 5 },
      { key: 'glabellar_lines', efficacy: 5 },
      { key: 'crows_feet', efficacy: 5 },
      { key: 'bunny_lines', efficacy: 4 },
      { key: 'brow_ptosis', efficacy: 3 },
    ],
    sessions: '1 次',
    interval: '3–4 個月',
    onset: '3–7 日',
    duration: '3–5 個月',
    downtimeDays: [0, 1],
    priceHKD: { min: 1500, max: 4500, unit: '每個部位' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕/哺乳', '神經肌肉疾病', '注射部位感染'],
    notes: '額紋只適合仍有彈性嘅動態紋；靜態深紋需配合填充或激光。眼皮下垂為已知風險。',
  },
  {
    id: 'btx-microtox',
    name: '微滴肉毒（水光肉毒）',
    brand: 'Micro-Botox / Mesobotox',
    category: 'injectable',
    family: '肉毒桿菌素 (Botulinum Toxin A)',
    mechanism: '極稀釋劑量淺層注射真皮，收細毛孔、減少油脂、提升皮膚光澤。',
    indications: [
      { key: 'pores', efficacy: 4 },
      { key: 'oiliness', efficacy: 4 },
      { key: 'texture', efficacy: 3 },
    ],
    sessions: '2–3 次',
    interval: '3–4 個月',
    onset: '2–3 星期',
    duration: '3–4 個月',
    downtimeDays: [0, 2],
    priceHKD: { min: 3000, max: 7000, unit: '每次（全面）' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕/哺乳', '神經肌肉疾病'],
  },
  {
    id: 'btx-neck',
    name: '肉毒頸紋 / Nefertiti Lift',
    brand: 'Botox / Dysport',
    category: 'injectable',
    family: '肉毒桿菌素 (Botulinum Toxin A)',
    mechanism: '放鬆闊頸肌向下拉力，令下顎線相對上提，並淡化橫向頸紋。',
    indications: [
      { key: 'neck_laxity', efficacy: 3 },
      { key: 'jawline_definition', efficacy: 3 },
    ],
    sessions: '1 次',
    interval: '4–6 個月',
    onset: '1–2 星期',
    duration: '4–6 個月',
    downtimeDays: [0, 1],
    priceHKD: { min: 4000, max: 9000, unit: '每次' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕/哺乳', '吞嚥困難病史', '神經肌肉疾病'],
  },

  // ────────────────────────── 透明質酸填充 ──────────────────────────
  {
    id: 'ha-midface',
    name: '透明質酸填充（中面部 / 蘋果肌）',
    brand: 'Juvederm Voluma / Restylane Lyft / Teosyal Ultra Deep',
    category: 'injectable',
    family: '透明質酸 (Hyaluronic Acid)',
    mechanism: '深層補充流失容積，重建中面部支撐，間接改善法令紋同下垂。',
    indications: [
      { key: 'midface_volume_loss', efficacy: 5 },
      { key: 'nasolabial_fold', efficacy: 4 },
      { key: 'skin_laxity', efficacy: 3 },
      { key: 'facial_asymmetry', efficacy: 4 },
    ],
    sessions: '1 次；視乎流失程度 1–3cc',
    interval: '12–18 個月補打',
    onset: '即時',
    duration: '12–24 個月',
    downtimeDays: [1, 5],
    priceHKD: { min: 4500, max: 9000, unit: '每 cc' },
    risk: 'high',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕/哺乳', '自體免疫疾病活躍期', '注射區感染或發炎', '對透明質酸/利多卡因過敏'],
    notes: '最嚴重風險為血管栓塞致皮膚壞死或失明；必須由熟悉解剖嘅醫生施行，並備有溶解酶。',
  },
  {
    id: 'ha-tear-trough',
    name: '透明質酸淚溝填充',
    brand: 'Restylane / Belotero Balance / Teosyal Redensity II',
    category: 'injectable',
    family: '透明質酸 (Hyaluronic Acid)',
    mechanism: '填補眼下凹陷，減少陰影造成嘅「黑眼圈」觀感。',
    indications: [
      { key: 'tear_trough', efficacy: 5 },
      { key: 'dark_circles', efficacy: 3 },
      { key: 'eye_bags', efficacy: 2 },
    ],
    sessions: '1 次',
    interval: '9–18 個月',
    onset: '即時，7–14 日穩定',
    duration: '9–18 個月',
    downtimeDays: [2, 7],
    priceHKD: { min: 4000, max: 8500, unit: '每 cc' },
    risk: 'high',
    regulation: DOCTOR_ONLY,
    contraindications: ['嚴重眼袋（脂肪疝出）', '甲狀腺眼病', '懷孕/哺乳', '注射區感染'],
    notes: '眼下皮膚薄，易現丁達爾效應（藍光）同水腫；色素型黑眼圈填充無效，需激光。',
  },
  {
    id: 'ha-chin-jaw',
    name: '透明質酸下巴 / 下顎線塑形',
    brand: 'Juvederm Volux / Restylane Defyne',
    category: 'injectable',
    family: '透明質酸 (Hyaluronic Acid)',
    mechanism: '高支撐力配方延長下巴、勾勒下顎線，改善側面線條同短下巴。',
    indications: [
      { key: 'chin_retrusion', efficacy: 5 },
      { key: 'jawline_definition', efficacy: 5 },
      { key: 'facial_asymmetry', efficacy: 3 },
    ],
    sessions: '1 次；一般 1–3cc',
    interval: '18–24 個月',
    onset: '即時',
    duration: '18–24 個月',
    downtimeDays: [1, 5],
    priceHKD: { min: 5500, max: 9500, unit: '每 cc' },
    risk: 'high',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕/哺乳', '注射區感染', '嚴重咬合問題（應先見牙科/正頜）'],
  },
  {
    id: 'ha-lip',
    name: '透明質酸豐唇',
    brand: 'Juvederm Volift / Restylane Kysse / Teosyal Kiss',
    category: 'injectable',
    family: '透明質酸 (Hyaluronic Acid)',
    mechanism: '增加唇部容積、修飾唇珠同唇緣線條。',
    indications: [
      { key: 'lip_volume', efficacy: 5 },
      { key: 'perioral_lines', efficacy: 3 },
    ],
    sessions: '1 次',
    interval: '9–15 個月',
    onset: '即時，7 日消腫',
    duration: '9–15 個月',
    downtimeDays: [3, 7],
    priceHKD: { min: 4000, max: 8000, unit: '每 cc' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['活躍唇皰疹', '懷孕/哺乳', '注射區感染'],
    notes: '有唇皰疹病史者宜術前預防性服抗病毒藥。',
  },
  {
    id: 'ha-temple',
    name: '透明質酸太陽穴填充',
    brand: 'Juvederm Voluma / Restylane Lyft',
    category: 'injectable',
    family: '透明質酸 (Hyaluronic Acid)',
    mechanism: '補充顳部凹陷，令上面部飽滿、面形更順滑。',
    indications: [
      { key: 'temple_hollow', efficacy: 5 },
      { key: 'brow_ptosis', efficacy: 2 },
    ],
    sessions: '1 次',
    interval: '12–24 個月',
    onset: '即時',
    duration: '12–24 個月',
    downtimeDays: [1, 4],
    priceHKD: { min: 4500, max: 9000, unit: '每 cc' },
    risk: 'high',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕/哺乳', '注射區感染'],
    notes: '顳部血管豐富，屬高風險區。',
  },

  // ────────────────────────── 膠原增生類 ──────────────────────────
  {
    id: 'ellanse',
    name: '少女針',
    brand: 'Ellansé (PCL)',
    category: 'injectable',
    family: '膠原增生劑 (Poly-caprolactone)',
    mechanism: '即時填充 + 持續刺激自體膠原新生，屬「即時 + 漸進」雙重效果。',
    indications: [
      { key: 'midface_volume_loss', efficacy: 5 },
      { key: 'nasolabial_fold', efficacy: 4 },
      { key: 'skin_laxity', efficacy: 4 },
      { key: 'marionette_lines', efficacy: 4 },
      { key: 'jawline_definition', efficacy: 3 },
      { key: 'temple_hollow', efficacy: 4 },
    ],
    sessions: '1 次；S(1年) / M(2年) / L(3年) 型號',
    interval: '按型號 12–36 個月',
    onset: '即時填充，膠原效果 1–3 個月',
    duration: '12–36 個月',
    downtimeDays: [2, 7],
    priceHKD: { min: 8000, max: 16000, unit: '每 cc' },
    risk: 'high',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕/哺乳', '自體免疫疾病', '疤痕增生體質', '注射區感染'],
    notes: '不可溶解（無解藥），打錯位置只能等代謝；務必揀有經驗醫生。',
  },
  {
    id: 'sculptra',
    name: '童顏針',
    brand: 'Sculptra (PLLA)',
    category: 'injectable',
    family: '膠原增生劑 (Poly-L-lactic Acid)',
    mechanism: '不作即時填充，靠聚左乳酸長期誘導膠原增生，全面自然回春。',
    indications: [
      { key: 'midface_volume_loss', efficacy: 4 },
      { key: 'skin_laxity', efficacy: 5 },
      { key: 'temple_hollow', efficacy: 4 },
      { key: 'nasolabial_fold', efficacy: 3 },
      { key: 'texture', efficacy: 3 },
    ],
    sessions: '2–3 次為一個療程',
    interval: '每次相隔 4–6 星期',
    onset: '6–12 星期漸進顯現',
    duration: '約 2 年',
    downtimeDays: [2, 5],
    priceHKD: { min: 8000, max: 15000, unit: '每支 (vial)' },
    risk: 'high',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕/哺乳', '疤痕增生/肉芽腫病史', '自體免疫疾病', '注射區感染'],
    notes: '需術後按摩（5-5-5 原則）減低結節風險。效果慢，唔適合趕時間。',
  },
  {
    id: 'radiesse',
    name: '晶亮瓷 / 少女針（CaHA）',
    brand: 'Radiesse (CaHA)',
    category: 'injectable',
    family: '膠原增生劑 (Calcium Hydroxylapatite)',
    mechanism: '鈣羥基磷灰石微球提供即時支撐並刺激膠原；稀釋後可作大面積緊膚。',
    indications: [
      { key: 'skin_laxity', efficacy: 4 },
      { key: 'jawline_definition', efficacy: 4 },
      { key: 'nasolabial_fold', efficacy: 4 },
      { key: 'marionette_lines', efficacy: 4 },
      { key: 'neck_laxity', efficacy: 3 },
    ],
    sessions: '1–2 次',
    interval: '12–18 個月',
    onset: '即時 + 3 個月膠原效果',
    duration: '12–18 個月',
    downtimeDays: [2, 6],
    priceHKD: { min: 6000, max: 11000, unit: '每 cc' },
    risk: 'high',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕/哺乳', '不建議用於唇部', '注射區感染'],
  },

  // ────────────────────────── 皮膚再生 / 水光 ──────────────────────────
  {
    id: 'rejuran',
    name: '嬰兒針（三文魚針）',
    brand: 'Rejuran / Rejuran I',
    category: 'injectable',
    family: '聚核苷酸 (Polynucleotide, PN)',
    mechanism: '三文魚 DNA 片段修復真皮、改善屏障、增加彈性同保濕，屬「養膚」而非填充。',
    indications: [
      { key: 'dehydration', efficacy: 5 },
      { key: 'texture', efficacy: 4 },
      { key: 'pores', efficacy: 3 },
      { key: 'acne_scar', efficacy: 3 },
      { key: 'dark_circles', efficacy: 3 },
      { key: 'redness', efficacy: 3 },
    ],
    sessions: '3–4 次為一個療程',
    interval: '每次相隔 2–4 星期',
    onset: '2–4 星期',
    duration: '6–12 個月（需維持）',
    downtimeDays: [1, 3],
    priceHKD: { min: 3000, max: 6500, unit: '每次 (2ml)' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['對三文魚/海鮮嚴重過敏', '懷孕/哺乳', '注射區感染'],
    notes: 'Rejuran I 為眼周專用配方。注射後短暫有小丘疹屬正常。',
  },
  {
    id: 'profhilo',
    name: '逆時針',
    brand: 'Profhilo',
    category: 'injectable',
    family: '高濃度透明質酸 (Bio-remodelling)',
    mechanism: '超高濃度 HA 於 5 個定點擴散，重塑水分同刺激多型膠原/彈性蛋白。',
    indications: [
      { key: 'dehydration', efficacy: 5 },
      { key: 'skin_laxity', efficacy: 4 },
      { key: 'texture', efficacy: 4 },
      { key: 'neck_laxity', efficacy: 3 },
    ],
    sessions: '2 次為一個療程',
    interval: '相隔 4 星期',
    onset: '4 星期',
    duration: '6–9 個月',
    downtimeDays: [1, 3],
    priceHKD: { min: 5500, max: 9500, unit: '每次' },
    risk: 'medium',
    regulation: DOCTOR_ONLY,
    contraindications: ['懷孕/哺乳', '注射區感染', '對透明質酸過敏'],
  },
  {
    id: 'skinbooster',
    name: '水光針',
    brand: 'Restylane Vital / Juvederm Volite / Neuramis Deep',
    category: 'injectable',
    family: '微量透明質酸注射 (Skin Booster)',
    mechanism: '真皮層微量多點注射透明質酸，提升含水量、光澤同細紋。',
    indications: [
      { key: 'dehydration', efficacy: 5 },
      { key: 'texture', efficacy: 4 },
      { key: 'pores', efficacy: 3 },
    ],
    sessions: '3 次為一個療程',
    interval: '每次相隔 3–4 星期',
    onset: '1–2 星期',
    duration: '4–6 個月',
    downtimeDays: [1, 3],
    priceHKD: { min: 1800, max: 4500, unit: '每次' },
    risk: 'low',
    regulation: DOCTOR_ONLY,
    contraindications: ['注射區感染或活躍暗瘡', '懷孕/哺乳'],
  },
  {
    id: 'exosome',
    name: '外泌體療程',
    brand: 'Exosome (ASCE+ / Cellcure 等)',
    category: 'injectable',
    family: '再生醫學 (Exosome)',
    mechanism: '幹細胞外泌體傳遞生長因子訊號，加速修復、抗炎、改善泛紅同暗瘡後皮膚。',
    indications: [
      { key: 'redness', efficacy: 4 },
      { key: 'pih', efficacy: 4 },
      { key: 'texture', efficacy: 4 },
      { key: 'acne_active', efficacy: 3 },
      { key: 'dehydration', efficacy: 3 },
    ],
    sessions: '3–5 次',
    interval: '每次相隔 2–4 星期',
    onset: '1–3 星期',
    duration: '視乎配合療程',
    downtimeDays: [0, 2],
    priceHKD: { min: 3000, max: 8000, unit: '每次' },
    risk: 'medium',
    regulation: '產品規管仍在演變中，選擇有清晰來源同認證嘅產品',
    contraindications: ['懷孕/哺乳', '活躍感染', '惡性腫瘤病史（需醫生評估）'],
    notes: '多數配合微針或激光導入。臨床證據仍在累積，宜以輔助角色定位。',
  },
  {
    id: 'lipolysis-chin',
    name: '溶脂針（頜下）',
    brand: 'Deoxycholic acid 類',
    category: 'injectable',
    family: '脂肪溶解注射',
    mechanism: '破壞脂肪細胞膜，經代謝清除頜下局部脂肪。',
    indications: [{ key: 'submental_fat', efficacy: 4 }],
    sessions: '2–4 次',
    interval: '每次相隔 4–6 星期',
    onset: '4–8 星期',
    duration: '脂肪細胞減少後屬長期，但體重增加仍會反彈',
    downtimeDays: [3, 10],
    priceHKD: { min: 3000, max: 7000, unit: '每次' },
    risk: 'high',
    regulation: '香港部分溶脂產品屬處方藥或未註冊，務必確認產品來源及由註冊醫生施行',
    contraindications: ['懷孕/哺乳', '吞嚥困難', '注射區感染', '頜下腫塊未確診'],
    notes: '腫脹明顯（可持續 1–2 星期）；有神經損傷致嘴角歪斜之報告。',
  },
];
